#
#	Configuration file support cmake
#

set(JCLIB_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(JCLIB_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(JCLIB_VERSION_PATCH ${PROJECT_VERSION_PATCH})

ADD_CONFIG_FILE("version.in.h")
