#pragma once
#ifndef JCLIB_CONFIG_VERSION_H
#define JCLIB_CONFIG_VERSION_H

#define JCLIB_VERSION_MAJOR ${JCLIB_VERSION_MAJOR}
#define JCLIB_VERSION_MINOR ${JCLIB_VERSION_MINOR}
#define JCLIB_VERSION_PATCH	${JCLIB_VERSION_PATCH}

#endif